package com.github.petarmitrovic.demoshop.dto;

import java.math.BigDecimal;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "A model used to pass information when creating and updating a product.")
public class ProductCommand {

    @ApiModelProperty(notes = "Stock keeping unit, a unique id of the product. " +
        "This field is ONLY considered when updating an existing product, while it's being generated by the system when creating a new one. ")
    private String sku;

    @ApiModelProperty(notes = "Product name")
    private String name;

    @ApiModelProperty(notes = "The price of this product")
    private BigDecimal price;

    public String getSku() {
        return sku;
    }

    public void setSku(String sku) {
        this.sku = sku;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }
}
